FORMAT: 1 A
HOST: http: //atgsoa12.kbace.com:7001/chub/data/resources/service/

#CHUB

CHUB REST API provides access to Cloud Central Conversions (ERP only).

#Group Requests

## Conversions Collection[/request]

###List All Conversion requests[GET]

+Response 200(application / json)

        [
        {
            "question": "Favourite programming language?",
            "published_at": "2015-08-05T08:40:51.620Z",
            "choices": [
            {
                "choice": "Swift",
                "votes": 2048
            },
            {
                "choice": "Python",
                "votes": 1024
            },
            {
                "choice": "Objective-C",
                "votes": 512
            },
            {
                "choice": "Ruby",
                "votes": 256
            }]
        }]

## Conversion Request by Key[/request/{requestId}]

### List specific Conversion request[GET]

+Response 200(application / json)

        {
            "request":
            {
                "requestId": 681,
                "creationDate": "2017-01-25",
                "createdBy": "admin-default",
                "lastUpdateDate": "2017-01-25",
                "lastUpdatedBy": "admin-default",
                "lastUpdateLogin": -1,
                "status": "RUNNING",
                "batchId": "20170125122345",
                "propertyFile": "test_win_properties.json",
                "errorFile": null,
                "propertyFileContent": "",
                "useBatchId": null,
                "usePropBatchId": null,
                "copyCat": null,
                "deleteCat": null,
                "runSIP": null,
                "sourceSys": null,
                "instType": "DEV",
                "entityRows": [
                {
                    "requestEntityId": 381,
                    "requestId": 681,
                    "entityShortName": "PUOR",
                    "operationType": "VAL",
                    "status": null,
                    "batchId": "20170125122345",
                    "copyCat": "N",
                    "deleteCat": "N",
                    "useBatchId": "20170124055938",
                    "runSIP": "N",
                    "entityFile": "PoImportOrders.zip",
                    "errorFile": "PoImportOrders.zip"
                }],
                "batchDataLogs": null
            }
        }

##Conversion Request Batch by Key[/request/batch/{batchId}]

### List specific Conversion batch for a request[GET]

+Response 200(application / json)

        [
        {
            "question": "Favourite programming language?",
            "published_at": "2015-08-05T08:40:51.620Z",
            "choices": [
            {
                "choice": "Swift",
                "votes": 2048
            },
            {
                "choice": "Python",
                "votes": 1024
            },
            {
                "choice": "Objective-C",
                "votes": 512
            },
            {
                "choice": "Ruby",
                "votes": 256
            }]
        }]

## Conversion Batch by Key[/batch/{batchId}]

### List specific Conversion batch[GET]

+Response 200(application / json)

        [
        {
            "question": "Favourite programming language?",
            "published_at": "2015-08-05T08:40:51.620Z",
            "choices": [
            {
                "choice": "Swift",
                "votes": 2048
            },
            {
                "choice": "Python",
                "votes": 1024
            },
            {
                "choice": "Objective-C",
                "votes": 512
            },
            {
                "choice": "Ruby",
                "votes": 256
            }]
        }]

## Conversion Creation[/requests]

### Submit a New Conversion[POST]

You may create your own question using this action.It takes a JSON object containing a question and a collection of answers in the form of choices.

+Request(application / json)

            {
                "question": "Favourite programming language?",
                "choices": [
                    "Swift",
                    "Python",
                    "Objective-C",
                    "Ruby"
                ]
            }

+Response 201(application/json)
+Headers  Location: /questions/2

+Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 0
                },
                {
                    "choice": "Python",
                    "votes": 0
                },
                {
                    "choice": "Objective-C",
                    "votes": 0
                },
                {
                    "choice": "Ruby",
                    "votes": 0
                }]
            }


#Group Validations

## Conversion Validation by Key[/validation/{validationId}]

### List specific Conversion Validation[GET]

+Response 200(application/json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]



## Entity Validatons Collection[/validation/{entityId}]

### List All Validations for an Entity[GET]

+Response 200(application / json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]


## Conversion Validation result by Entity Key[/validation/result/{entityId}]

### List specific Conversion Validation result for an Entity[GET]

+Response 200(application / json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]


#Group Reports
## Conversions Status Report[/report/conversion / status]

### List All Conversion requests status count[GET]

            +
            Response 200(application / json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]

## Conversions Status Report[/report/conversion / entity / count]

### List All Conversion requests entity count[GET]

            +Response 200(application / json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]


## Conversions Status Report[/report/conversion/customer/count]

### List All Conversion requests customer count[GET]

            +Response 200(application / json)

            [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                },
                {
                    "choice": "Python",
                    "votes": 1024
                },
                {
                    "choice": "Objective-C",
                    "votes": 512
                },
                {
                    "choice": "Ruby",
                    "votes": 256
                }]
            }]